#!/usr/bin/env bash

# ecukes --- Cucumber for Emacs

# Copyright (C) 2010-2012 Johan Andersson
# Copyright (C) 2012 Joel McCracken
# Copyright (C) 2012 Dave Paroulek

# Author: Johan Andersson <johan.rejeep@gmail.com>
# Maintainer: Johan Andersson <johan.rejeep@gmail.com>
# Version: 0.2.1
# Keywords: testing, cucumber
# URL: http://ecukes.info

# This file is NOT part of GNU Emacs.

# License:

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with GNU Emacs; see the file COPYING.  If not, write to the
# Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

ECUKES_HOME=$(dirname $BASH_SOURCE)
ECUKES_EL=$ECUKES_HOME/ecukes-term.el
ECUKES_NEW=$ECUKES_HOME/ecukes-new.el

if [ -z "$ECUKES_EMACS" ] ; then
  if [ -z "$EMACS" ] ; then
    ECUKES_EMACS="emacs"
  else
    ECUKES_EMACS="$EMACS"
  fi
fi

if [ "$1" == "-h" -o "$1" == "--help" ] ; then
  cat $ECUKES_HOME/templates/usage.tpl
elif [ "$1" == "--new" ] ; then
  "$ECUKES_EMACS" --script "$ECUKES_NEW" --eval "(ecukes-new)"
elif [ "$1" == "--script" ] ; then
  "$ECUKES_EMACS" --script "$ECUKES_EL" "${@:2}"
else
  export ECUKES_OUTFILE=$(mktemp /tmp/ecukes.XXX)
  
  if [[ "$1" == "--win" ]]; then
    "$ECUKES_EMACS" --load "$ECUKES_EL" -Q "$@"
  else
    "$ECUKES_EMACS" -nw --load "$ECUKES_EL" -Q "$@"
  fi

  STATUS=$?

  cat $ECUKES_OUTFILE
  rm -f $ECUKES_OUTFILE

  exit $STATUS
fi
